version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: './workflows'
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
