version: '3'

services:
  mysql:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --accesslog
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wordpress:
    image: wordpress:php8.0
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./wordpress:/var/www/html
    expose:
      - 80
      - 443
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_URL}`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE', false);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_DEBUG_LOG', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('HEADLESS_FRONTEND_URL', '${HEADLESS_FRONTEND_URL}');
        define('PREVIEW_SECRET_TOKEN', '${PREVIEW_SECRET_TOKEN}');
        define('WP_SITEURL', 'https://${WORDPRESS_URL}');
        define('WP_HOME', 'https://${WORDPRESS_URL}');

  wpcli:
    image: wordpress:cli-php8.0
    depends_on:
      - wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./setup.sh:/var/www/html/setup.sh
      - ./.env:/var/www/html/.env
    user: xfs
    command: tail -f /dev/null;
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST}
      PMA_USER: ${WORDPRESS_DB_USER}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  composer:
    image: composer:latest
    command: >
      /bin/sh -c '
      sleep 20;
      composer upgrade;
      tail -f /dev/null;
      '
    volumes:
      - ./:/app

volumes:
  mysql: {}
  wordpress: {}
